# -*- coding: utf-8 -*-
"""WordCloud Feedback Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bvNu5G0O8SNQry6Dltn6VZc-pH05G2hL
"""

import pandas as pd

df = pd.read_csv(r"/content/Restaurant_Reviews.tsv", delimiter = "\t")

df.head()

"""**WORD CLOUD SECTION**"""

# Commented out IPython magic to ensure Python compatibility.
# Start with loading all necessary libraries
import numpy as np
from os import path
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

import matplotlib.pyplot as plt
# % matplotlib inline

df.shape #1000 rows and 2 columns

# Start with one review:
text = df.Review[0]

# Create and generate a word cloud image:
wordcloud = WordCloud().generate(text)

# Display the generated image:
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

# lower max_font_size, change the maximum number of word and lighten the background:
wordcloud = WordCloud(max_font_size=50, max_words=100, background_color="white").generate(text)
plt.figure()
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

# Doing it for all the columns now
text = " ".join(review for review in df.Review)
print ("There are {} words in the combination of all review.".format(len(text)))

#text
str_list = text.split()
unique_words = set(str_list)
wrds = list()
for words in unique_words :
        #print('Frequency of ', words , 'is :', str_list.count(words))
        if(str_list.count(words) > 20):
          wrds.append(words)
print(wrds)

# Creating stopword list:
stopwords = set(STOPWORDS)
stopwords.update(['would', 'my', 'were', 'on', 'to', 'but', "don't", 'great', 'go', 'our', 'it', 'in', 'all', 'will', 'this', 'We', 'as', 'The', 'of', 'really', 'that', 'for', 'just', 'here', 'is', 'and', 'with', 'very', 'their', 'have', 'was', 'only', 'a', 'This', 'they', 'your', 'from', 'at', 'It', '-', 'like', 'back', 'an', 'you', 'service', 'are', 'had', 'the', 'not', 'we', 'ever', 'time', 'also', 'good', 'been', 'so', 'be', 'there', 'place', 'good.', 'I', 'food']

)
# Generate a word cloud image
wordcloud = WordCloud(stopwords=stopwords, background_color="white", max_words=40).generate(text)

# Display the generated image:
# the matplotlib way:
plt.figure(figsize=(12,8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""**COUNT OF LIKES AND DISLIKES**"""

review_result = df.groupby("Liked")         # Group the Likes and Dislikes - Liked Column

review_result.describe()

plt.figure(figsize=(12,8))
review_result.size().sort_values(ascending=False).plot.bar()
plt.xticks(rotation=0)
plt.xlabel("Likes - 1, Dislikes - 0")
plt.ylabel("Number of Likes / Dislikes")
plt.show()

